#!/usr/bin/env python3
"""Second GEO batch: Sherbrooke quartiers, extra towns, product pages, more articles."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from write_geo_batch import write_article, write_service
from write_top_regions import render as render_region

ROOT = Path(__file__).resolve().parent.parent

REGIONS = [
    {
        "slug": "lennoxville",
        "name": "Lennoxville",
        "title": "Courtier immobilier à Lennoxville | CDF",
        "description": "Acheter ou vendre à Lennoxville (Sherbrooke) : village universitaire, unifamiliales et multiplex. Équipe Chiasson de Francesco.",
        "h1": "Acheter ou vendre une propriété à Lennoxville",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Lennoxville : le village universitaire de Sherbrooke, ses rues résidentielles, ses plex près du campus et un marché bilingue.",
        "intro": "Lennoxville n'est pas Fleurimont. C'est un ancien village fusionné à Sherbrooke, avec Bishop's, un centre marchable et beaucoup d'acheteurs qui veulent ce cadre : pas seulement un code postal J1M.",
        "sections": [
            ("Village universitaire", "Le noyau (Queen, College, rues autour du campus) attire étudiants, profs et ménages qui veulent marcher. Plus loin, des unifamiliales et quelques rues plus calmes. Les plex près du campus se jugent aux loyers réels et à l'état, pas à un rendement « universitaire » copié."),
            ("Acheter à Lennoxville", "Bâtiments souvent plus anciens, stationnement parfois serré, zonage mixte par endroits. Comparez des ventes Lennoxville, pas Mont-Bellevue. Marco travaille en anglais, utile ici."),
            ("Vendre à Lennoxville", "Misez sur le village et l'accès aux services, pas sur un prix « Sherbrooke moyen ». Un plex mal chiffré reste en inventaire. Photos du quartier et dossier locatif clair aident."),
        ],
        "related": [("Sherbrooke", "sherbrooke.html"), ("Fleurimont", "fleurimont.html"), ("Les Nations", "les-nations.html"), ("Plex à Sherbrooke", "../plex-sherbrooke.html")],
        "faqs": [
            ("Lennoxville fait-il encore partie de Sherbrooke ?", "Oui, c'est un arrondissement de Sherbrooke. Pour l'acheteur, le quotidien reste celui d'un village : commerces de proximité, campus, et un marché distinct de Fleurimont ou Rock Forest."),
            ("Bon secteur pour un plex ?", "Près du campus, la demande locative étudiante existe, mais les immeubles sont souvent plus vieux. Loyers, rénos et règlement de copropriété s'il y a division. Pas un rendement automatique."),
            ("Faut-il parler anglais ?", "Utile. Lennoxville est historiquement bilingue. L'équipe Chiasson de Francesco travaille en français et en anglais."),
            ("Moins cher que le centre-ville ?", "Parfois pour une unifamiliale, pas toujours pour un plex rénové. On compare des ventes du village, pas une moyenne sherbrookoise."),
        ],
    },
    {
        "slug": "fleurimont",
        "name": "Fleurimont",
        "title": "Courtier immobilier à Fleurimont | Sherbrooke | CDF",
        "description": "Maisons à Fleurimont, Sherbrooke : quartiers familiaux, bungalows et accès hôpital. Courtiers Chiasson de Francesco.",
        "h1": "Acheter ou vendre une propriété à Fleurimont",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Fleurimont : arrondissement familial de Sherbrooke, bungalows, rues calmes et proximité du CHUS.",
        "intro": "Fleurimont est souvent le premier réflexe des familles qui veulent une unifamiliale à Sherbrooke sans payer un village lacustre. Ce n'est pas Lennoxville, ni Les Nations condos.",
        "sections": [
            ("Quartiers familiaux", "Beaucoup de rues de bungalows et de cottages, écoles de proximité, accès 410. L'hôpital (CHUS Fleurimont) structure une partie de la demande. Les micro-secteurs n'ont pas tous le même âge de bâtiment ni le même terrain."),
            ("Acheter à Fleurimont", "Inspection (toitures, fondations des années 60-80), et comparables de la même poche de rues. Un « Fleurimont » trop large dans l'annonce cache parfois un bien trop cher pour sa rue."),
            ("Vendre à Fleurimont", "Le volume d'unifamiliales est plus élevé qu'à North Hatley : le prix d'inscription se voit tout de suite. Photos, état, et un prix collé aux ventes récentes du même type de bungalow."),
        ],
        "related": [("Sherbrooke", "sherbrooke.html"), ("Rock Forest", "rock-forest.html"), ("Mont-Bellevue", "mont-bellevue.html"), ("Première maison", "../article-premiere-maison-estrie.html")],
        "faqs": [
            ("Fleurimont est-il un bon quartier pour une première maison ?", "Souvent oui : plus d'unifamiliales, services, et un budget parfois plus sage que Magog lac ou Lennoxville village. Visitez le soir et un samedi. L'inspection reste non négociable."),
            ("Proche de l'hôpital, ça change le prix ?", "La proximité du CHUS intéresse certains acheteurs (quart de travail, famille). Ce n'est pas un bonus automatique de 50 000 $. Les ventes de la rue tranchent."),
            ("Fleurimont ou Rock Forest ?", "Fleurimont est plus « ville et services ». Rock Forest a souvent plus de terrain et un caractère plus à l'ouest. Le trajet quotidien décide autant que le prix au pied carré."),
            ("Vous vendez à Fleurimont ?", "Oui. C'est le quotidien de l'équipe Chiasson de Francesco, basée à Sherbrooke."),
        ],
    },
    {
        "slug": "rock-forest",
        "name": "Rock Forest",
        "title": "Courtier à Rock Forest–Saint-Élie–Deauville | CDF",
        "description": "Acheter ou vendre à Rock Forest, Sherbrooke : maisons, terrains plus grands, accès Magog. Équipe Chiasson de Francesco.",
        "h1": "Acheter ou vendre à Rock Forest",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Rock Forest (arrondissement Rock Forest–Saint-Élie–Deauville) : unifamiliales, plus de terrain qu'en centre-ville, axe vers Magog.",
        "intro": "Rock Forest est l'ouest de Sherbrooke : moins dense que Les Nations, plus de lots, et un pied vers Magog. Saint-Élie n'est pas la même poche que les rues près de la 112. Deauville, côté Magog, se discute à part.",
        "sections": [
            ("Plus de terrain, autre rythme", "Beaucoup d'acheteurs y voient un compromis ville/espace. Les rues n'ont pas toutes les mêmes services (égouts vs fosse selon le secteur). Un prix « Rock Forest » unique n'existe pas."),
            ("Acheter à Rock Forest", "Vérifiez le type de lot, le drainage, et le temps réel vers le travail (Sherbrooke centre ou Magog). Comparables du même micro-secteur. Inspection des bâtiments des années 70-90 fréquente."),
            ("Vendre à Rock Forest", "Photos du terrain et de la saison. Ne pas coller un prix Magog lac ni un prix Les Nations condo. Le volume est là si le prix est juste."),
        ],
        "related": [("Sherbrooke", "sherbrooke.html"), ("Fleurimont", "fleurimont.html"), ("Magog", "magog.html"), ("Navette", "../article-navette-sherbrooke.html")],
        "faqs": [
            ("Rock Forest, c'est encore Sherbrooke ?", "Oui, arrondissement de Sherbrooke. Pour l'acheteur, le quotidien est plus dispersé que le centre-ville : auto presque indispensable, plus d'espace."),
            ("Moins cher que Fleurimont ?", "Parfois, surtout avec plus de terrain. Un cottage rénové peut dépasser un bungalow fleurimontois. On compare des ventes, pas des étiquettes d'arrondissement."),
            ("Proche de Magog ?", "Oui, c'est souvent le point. Mesurez le trajet aux heures de pointe, pas seulement la carte."),
            ("Desservez-vous Saint-Élie aussi ?", "Oui. L'arrondissement entier fait partie du territoire de l'équipe."),
        ],
    },
    {
        "slug": "les-nations",
        "name": "Les Nations",
        "title": "Courtier Les Nations Sherbrooke | condos et centre | CDF",
        "description": "Condos, plex et centre-ville aux Nations, Sherbrooke. Acheter ou vendre avec l'équipe Chiasson de Francesco, RE/MAX.",
        "h1": "Acheter ou vendre aux Nations (Sherbrooke)",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente dans l'arrondissement Les Nations : condos du centre, plex, locaux sur Wellington et King, et un marché plus urbain que Fleurimont.",
        "intro": "Les Nations, c'est le cœur dense de Sherbrooke : rivière, universités à proximité, condos, plex et commercial de rue. Un penthouse n'est pas un 4½ des années 70. Les charges de copropriété décident autant que la vue.",
        "sections": [
            ("Centre, rivière, artères", "King, Wellington, rives : plus de condos et de plex. Stationnement, bruits de rue et règlements de copropriété (animaux, location) se lisent avant l'offre. Côté commercial, l'équipe inscrit aussi des locaux et bâtisses."),
            ("Acheter aux Nations", "Dossier de copropriété complet, fonds de prévoyance, PV. Pour un plex : baux, loyers réels, état. Voir nos guides condo et plex. Ne comparez pas un condo neuf avec un plex non rénové."),
            ("Vendre aux Nations", "Le dossier (charges, fonds, stationnement) se prépare avant l'affiche. Un prix calqué sur « le centre a monté » sans ventes comparables allonge l'affichage."),
        ],
        "related": [("Sherbrooke", "sherbrooke.html"), ("Lennoxville", "lennoxville.html"), ("Condo à Sherbrooke", "../article-condo-sherbrooke.html"), ("Commercial", "../courtier-commercial.html")],
        "faqs": [
            ("Les Nations, c'est le centre-ville ?", "C'est l'arrondissement qui englobe le centre et plusieurs quartiers denses. « Centre-ville » dans une annonce peut vouloir dire trois rues différentes. On précise le secteur."),
            ("Bon pour un premier condo ?", "Oui si vous lisez les charges et le fonds. Un prix bas avec des cotisations qui s'en viennent n'est pas une aubaine. Notre article condo détaille quoi demander."),
            ("Vous avez des inscriptions aux Nations ?", "Oui, selon le moment : dont des adresses King / Wellington. Voyez la page propriétés."),
            ("Plex ou condo ?", "Deux analyses. Le plex, c'est du locatif et de l'entretien. Le condo, c'est des charges et un syndicat. L'équipe fait les deux lectures."),
        ],
    },
    {
        "slug": "brompton",
        "name": "Brompton",
        "title": "Courtier immobilier à Brompton | Sherbrooke | CDF",
        "description": "Maisons à Brompton (Sherbrooke), vallée de la Saint-François. Acheter ou vendre avec Chiasson de Francesco.",
        "h1": "Acheter ou vendre une propriété à Brompton",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Brompton : arrondissement nord de Sherbrooke, unifamiliales, caractère de petite ville et axe vers Windsor.",
        "intro": "Brompton (Bromptonville) a gardé une identité de ville de vallée, même fusionnée à Sherbrooke. Ce n'est pas Fleurimont, ni Windsor. Les comparables doivent rester Brompton.",
        "sections": [
            ("Petite ville dans la ville", "Noyau, rues résidentielles, proximité de la Saint-François. Moins de condos que Les Nations. Beaucoup d'acheteurs y voient un budget plus accessible que certains quartiers sud, avec un temps de route vers le centre."),
            ("Acheter à Brompton", "Inspection, et trajet réel vers le travail. Comparables Brompton, pas Richmond. Un plex se juge aux loyers du secteur, plus petits qu'au centre-ville."),
            ("Vendre à Brompton", "Le « 10 minutes de Sherbrooke » n'excuse pas un prix des Nations. Photos claires, prix de Brompton."),
        ],
        "related": [("Sherbrooke", "sherbrooke.html"), ("Windsor", "windsor.html"), ("Fleurimont", "fleurimont.html"), ("Navette", "../article-navette-sherbrooke.html")],
        "faqs": [
            ("Brompton ou Windsor ?", "Brompton est un arrondissement de Sherbrooke ; Windsor est une autre ville. Taxes, services et comparables changent. Le trajet vers le centre de Sherbrooke est souvent plus court depuis Brompton."),
            ("Moins cher que Fleurimont ?", "Souvent pour une unifamiliale comparable, avec moins de densité. L'état du bâtiment pèse plus que le nom de l'arrondissement."),
            ("Bon pour navetter ?", "Oui pour plusieurs. Mesurez l'heure de pointe, pas le dimanche."),
            ("Vous travaillez Brompton ?", "Oui. Vallée de la Saint-François : Brompton, Windsor, Richmond."),
        ],
    },
    {
        "slug": "mont-bellevue",
        "name": "Mont-Bellevue",
        "title": "Courtier Mont-Bellevue Sherbrooke | CDF",
        "description": "Unifamiliales et rues résidentielles à Mont-Bellevue, Sherbrooke. Équipe Chiasson de Francesco, RE/MAX D'ABORD.",
        "h1": "Acheter ou vendre à Mont-Bellevue",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Mont-Bellevue : arrondissement de Sherbrooke, unifamiliales, parc du mont et un marché plus résidentiel que le centre-ville.",
        "intro": "Mont-Bellevue, c'est surtout de la maison : rues familiales, accès au parc du mont, moins de condos que Les Nations. Un bungalow ici ne se compare pas à un condo King.",
        "sections": [
            ("Rues et parc", "Le mont et le parc structurent une partie du cadre de vie. Les poches de rues n'ont pas le même âge ni le même terrain. L'université (campus) est proche sans que tout le quartier soit « étudiant » comme Lennoxville."),
            ("Acheter à Mont-Bellevue", "Comparables du même type de rue. Inspection des cottages et bungalows. Stationnement et pente selon le secteur."),
            ("Vendre à Mont-Bellevue", "Photos du quartier et de l'intérieur. Prix ancré sur Mont-Bellevue, pas sur un condo des Nations ni un village lacustre."),
        ],
        "related": [("Sherbrooke", "sherbrooke.html"), ("Fleurimont", "fleurimont.html"), ("Lennoxville", "lennoxville.html"), ("Les Nations", "les-nations.html")],
        "faqs": [
            ("Mont-Bellevue ou Fleurimont ?", "Deux arrondissements familiaux, deux grilles de comparables. Mont-Bellevue a le parc du mont ; Fleurimont a l'hôpital. Visitez les deux plutôt que de choisir sur une moyenne."),
            ("Beaucoup de condos ?", "Moins qu'aux Nations. Le stock dominant, c'est l'unifamiliale. Un condo isolé se compare à d'autres copropriétés du même type, pas au bungalow d'à côté."),
            ("Proche de l'université ?", "Le campus influence certaines rues, pas tout l'arrondissement. Distinguez location étudiante et résidence familiale dans le prix."),
            ("Vous vendez à Mont-Bellevue ?", "Oui. L'équipe est basée à Sherbrooke et y travaille au quotidien."),
        ],
    },
    {
        "slug": "ayers-cliff",
        "name": "Ayer's Cliff",
        "title": "Courtier immobilier à Ayer's Cliff | lac Massawippi | CDF",
        "description": "Maisons et bord de lac à Ayer's Cliff, Estrie. L'équipe Chiasson de Francesco vous accompagne au Massawippi.",
        "h1": "Acheter ou vendre une propriété à Ayer's Cliff",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Ayer's Cliff : village du lac Massawippi, distinct de North Hatley, avec un marché bilingue et souvent plus de villégiature.",
        "intro": "Ayer's Cliff partage le lac avec North Hatley sans en avoir le même cachet village ni les mêmes prix. Une rive n'est pas l'autre. Calquer un prix Hatley ici (ou l'inverse) est une erreur fréquente.",
        "sections": [
            ("Village et rives", "Le village est compact. Les rives et les rangs autour se négocient sur l'accès à l'eau, la fosse, et la saisonnalité. Ce n'est pas Magog centre."),
            ("Acheter à Ayer's Cliff", "Titres, bandes riveraines, quatre-saisons vs chalet. Inspection. Marco est bilingue, utile dans ce secteur."),
            ("Vendre à Ayer's Cliff", "Photos d'eau et de saison. Comparables Ayer's Cliff / Massawippi sud, pas Knowlton ni Memphrémagog Magog."),
        ],
        "related": [("North Hatley", "north-hatley.html"), ("Lac Massawippi", "lac-massawippi.html"), ("Stanstead", "stanstead.html"), ("Bord de lac", "../article-bord-de-lac-estrie.html")],
        "faqs": [
            ("Ayer's Cliff est-il moins cher que North Hatley ?", "Souvent pour un bien comparable, le village Hatley se paie plus cher. Une vraie rive bien située à Ayer's Cliff reste un produit rare. Comparez rive par rive."),
            ("Résidence principale ou chalet ?", "Les deux existent. Isolation, chauffage et accès hivernal tranchent. L'annonce « quatre-saisons » se vérifie à l'inspection."),
            ("Secteur bilingue ?", "Oui. L'équipe travaille en français et en anglais."),
            ("Vous allez à Ayer's Cliff ?", "Oui, avec North Hatley et le Massawippi."),
        ],
    },
    {
        "slug": "austin",
        "name": "Austin",
        "title": "Courtier immobilier à Austin | près d'Orford | CDF",
        "description": "Maisons et chalets à Austin, Estrie, entre Magog et le mont Orford. Équipe Chiasson de Francesco.",
        "h1": "Acheter ou vendre une propriété à Austin",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Austin : municipalité entre Magog, Eastman et Orford, maisons, chalets et cadre plus champêtre que Magog centre.",
        "intro": "Austin vit dans l'orbite du Memphrémagog et d'Orford sans être une ville de services. Peu d'inscriptions, beaucoup de villégiature et de résidences avec terrain. Un prix Magog condo ne s'applique pas.",
        "sections": [
            ("Entre Magog et la montagne", "Rangs, chalets, quelques maisons de village. Eastman et Orford encadrent les comparables. L'accès au lac n'est pas automatique parce que « Austin » est dans l'annonce."),
            ("Acheter à Austin", "Fosses, puits, accès hivernal, zonage. Un trois-saisons n'est pas une résidence principale. Inspection avant l'offre."),
            ("Vendre à Austin", "Photos de saison, honnêteté sur l'eau et les services. Prix Austin/Orford rural, pas Georgeville frontage."),
        ],
        "related": [("Orford", "orford.html"), ("Eastman", "eastman.html"), ("Magog", "magog.html"), ("Chalet en Estrie", "../chalet-estrie.html")],
        "faqs": [
            ("Austin ou Eastman ?", "Deux municipalités proches, deux stocks. Eastman a un village plus « destination ». Austin est souvent plus dispersé. Visitez plutôt que de choisir sur le nom."),
            ("Peut-on habiter à l'année ?", "Oui si le bâtiment et l'accès le permettent. Beaucoup de chalets restent saisonniers. L'inspection tranche."),
            ("Proche du ski Orford ?", "Dans l'orbite, pas au pied des pistes. Un condo Orford et une maison Austin ne se comparent pas."),
            ("Desservez-vous Austin ?", "Oui. Corridor Magog–Orford–Eastman–Austin."),
        ],
    },
    {
        "slug": "waterville",
        "name": "Waterville",
        "title": "Courtier immobilier à Waterville | Estrie | CDF",
        "description": "Acheter ou vendre à Waterville, entre Sherbrooke et Coaticook. Courtiers Chiasson de Francesco.",
        "h1": "Acheter ou vendre une propriété à Waterville",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Waterville : village entre Sherbrooke, Compton et Coaticook, unifamiliales et quelques lots plus grands.",
        "intro": "Waterville est un petit marché de village : moins d'inscriptions que Sherbrooke, plus de services que Compton rang. Un prix « 15 minutes de Sherbrooke » sans comparables Waterville ne tient pas.",
        "sections": [
            ("Village-relais", "Noyau, rues résidentielles, axe vers Coaticook et Lennoxville. Ce n'est ni le campus ni Fleurimont."),
            ("Acheter à Waterville", "Inspection, fosses hors réseau selon l'adresse, comparables Waterville/Compton village. Trajet vers Sherbrooke à valider aux heures de pointe."),
            ("Vendre à Waterville", "Marché mince : le premier prix compte. Photos honnêtes, affichage Estrie."),
        ],
        "related": [("Compton", "compton.html"), ("Coaticook", "coaticook.html"), ("Lennoxville", "lennoxville.html"), ("Sherbrooke", "sherbrooke.html")],
        "faqs": [
            ("Waterville est-il moins cher que Sherbrooke ?", "Souvent pour une unifamiliale, avec moins de services urbains. L'écart dépend de l'état et du lot."),
            ("Bon compromis vers Coaticook ?", "Oui pour qui travaille ou a de la famille vers le Haut-Saint-François, tout en restant plus près de Sherbrooke que Coaticook centre."),
            ("Beaucoup de maisons à vendre ?", "Peu. Quand une inscription sort, elle doit être au bon prix dès le jour 1."),
            ("Vous allez à Waterville ?", "Oui, avec Compton, Coaticook et Lennoxville."),
        ],
    },
    {
        "slug": "hatley",
        "name": "Hatley",
        "title": "Courtier immobilier à Hatley | Cantons-de-l'Est | CDF",
        "description": "Propriétés à Hatley, près de North Hatley et du Massawippi. Équipe Chiasson de Francesco, Estrie.",
        "h1": "Acheter ou vendre une propriété à Hatley",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Hatley : municipalité distincte de North Hatley, rangs, maisons de campagne et orbite du lac Massawippi.",
        "intro": "Hatley (le canton) n'est pas le village de North Hatley. Confondre les deux dans un prix d'affichage est une erreur classique. Plus de terrain, moins de vitrine touristique.",
        "sections": [
            ("Canton vs village", "North Hatley = village lacustre serré. Hatley = plus rural. Les comparables ne se mélangent pas, même si le code postal et le lac sont proches."),
            ("Acheter à Hatley", "Zonage, fosses, acreage, accès hivernal. Un lot « vue lac » sans droits d'eau se paie autrement. Inspection des bâtiments de ferme ou de campagne."),
            ("Vendre à Hatley", "Ne pas afficher un prix North Hatley village. Photos de saison et acreage honnête."),
        ],
        "related": [("North Hatley", "north-hatley.html"), ("Ayer's Cliff", "ayers-cliff.html"), ("Lac Massawippi", "lac-massawippi.html"), ("Fermette", "../fermette-estrie.html")],
        "faqs": [
            ("Hatley et North Hatley, c'est la même chose ?", "Non. North Hatley est le village. Hatley est une municipalité distincte, plus rurale. Les acheteurs confondent souvent ; un courtier ne le fait pas dans les comparables."),
            ("Moins cher que North Hatley ?", "En général pour une maison sans lac, oui. Un vrai frontage reste un autre produit."),
            ("Secteur bilingue ?", "Oui, comme beaucoup du Massawippi. L'équipe travaille FR/EN."),
            ("Desservez-vous Hatley ?", "Oui, avec tout le corridor Massawippi."),
        ],
    },
    {
        "slug": "milan",
        "name": "Milan",
        "title": "Courtier immobilier à Milan | Estrie | CDF",
        "description": "Acheter ou vendre à Milan, Estrie (MRC du Granit). L'équipe Chiasson de Francesco y inscrit aussi des propriétés.",
        "h1": "Acheter ou vendre une propriété à Milan",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Milan, petite municipalité du Granit : maisons, rangs, et un marché local distinct de Sherbrooke : l'équipe y a notamment inscrit des unifamiliales.",
        "intro": "Milan n'est pas un quartier de Sherbrooke. C'est un marché mince du Granit, plus près de Lac-Mégantic que de Magog. Les comparables doivent rester locaux. Quand l'équipe a un mandat ici, le prix se cale sur Milan, pas sur Fleurimont.",
        "sections": [
            ("Village du Granit", "Peu de volume, acheteurs surtout régionaux. Une maison « abordable » sur Centris n'est une affaire que si l'état et le puits/fosse suivent."),
            ("Acheter à Milan", "Inspection, installations septiques, trajet vers les services (Lac-Mégantic ou ailleurs). Comparables Milan/Granit."),
            ("Vendre à Milan", "Affichage régional depuis Sherbrooke aide à trouver l'acheteur. Une surcote « parce que l'Estrie a monté » n'accélère rien."),
        ],
        "related": [("Lac-Mégantic", "lac-megantic.html"), ("Lac Aylmer", "lac-aylmer.html"), ("Propriétés", "../proprietes.html"), ("Vendre", "../vendre.html")],
        "faqs": [
            ("Pourquoi une équipe de Sherbrooke à Milan ?", "Parce que des propriétaires nous y confient des mandats. Le bureau est à Sherbrooke ; le déplacement se fait quand le dossier le justifie. Voyez les fiches actives sur la page propriétés."),
            ("Marché actif ?", "Non. Peu d'inscriptions. Le prix d'entrée est le levier."),
            ("Fermette ou village ?", "Les deux peuvent exister. Terre et bâtiments se négocient à part d'une maison de village."),
            ("Loin pour les visites ?", "Oui par rapport à Fleurimont. On organise les visites, on ne fait pas semblant que c'est le coin de la rue."),
        ],
    },
    {
        "slug": "saint-isidore-de-clifton",
        "name": "Saint-Isidore-de-Clifton",
        "title": "Courtier à Saint-Isidore-de-Clifton | fermettes | CDF",
        "description": "Fermettes et rangs à Saint-Isidore-de-Clifton, Estrie. L'équipe Chiasson de Francesco y accompagne achat et vente.",
        "h1": "Acheter ou vendre à Saint-Isidore-de-Clifton",
        "lead": "L'équipe Chiasson de Francesco accompagne l'achat et la vente à Saint-Isidore-de-Clifton : fermettes, rangs du Haut-Saint-François, un marché rural où l'acreage et les bâtiments pèsent plus que le code postal.",
        "intro": "Saint-Isidore-de-Clifton n'est pas Coaticook centre. C'est du rural : peu d'inscriptions, beaucoup de terre et de dépendances. L'équipe y a notamment inscrit des fermettes : le prix se justifie par les ventes agricoles comparables, pas par un rêve de domaine.",
        "sections": [
            ("Rangs et fermettes", "Superficie, type de sol, bâtiments (grange, atelier), zonage agricole. Une « belle vue » ne paie pas une toiture de grange à refaire."),
            ("Acheter ici", "Titres, CPTAQ au besoin, fosse, puits, inspection des bâtiments hors maison. Voir aussi notre page fermette. Un notaire et parfois un agronome valent plus qu'une clause copiée."),
            ("Vendre ici", "Photos de saison, acreage exact, bâtiments décrits sans marketing excessif. Comparables Clifton/Coaticook rural, pas Magog lac."),
        ],
        "related": [("Coaticook", "coaticook.html"), ("Compton", "compton.html"), ("Fermette en Estrie", "../fermette-estrie.html"), ("Propriétés", "../proprietes.html")],
        "faqs": [
            ("Puis-je habiter une fermette sans être producteur ?", "Selon le zonage et les usages permis. Certaines terres agricoles restreignent ce que vous pouvez faire. Vérifiez avant d'offrir, pas après."),
            ("Pourquoi si cher à l'acre ?", "Souvent ce n'est pas cher à l'acre une fois les bâtiments et la qualité de terre déduits : ou l'inverse. Un courtier rural sépare les deux."),
            ("Vous vous déplacez jusque-là ?", "Oui, pour les mandats du Haut-Saint-François, dont des fermettes déjà inscrites par l'équipe."),
            ("Inspection différente d'une maison en ville ?", "Oui : grange, drainage, équipements, fosse dimensionnée pour le site. Budgetz un inspecteur qui connaît le rural."),
        ],
    },
]

SERVICES = [
    {
        "file": "fermette-estrie.html",
        "title": "Vendre ou acheter une fermette en Estrie | CDF",
        "desc": "Fermettes en Estrie : acreage, zonage agricole, bâtiments. L'équipe Chiasson de Francesco accompagne Coaticook, Clifton, Compton.",
        "h1": "Acheter ou vendre une fermette en Estrie",
        "lead": "L'équipe Chiasson de Francesco accompagne fermettes et propriétés avec terre en Estrie : Coaticook, Compton, Saint-Isidore-de-Clifton et rangs du Haut-Saint-François : un produit distinct d'une unifamiliale de Fleurimont.",
        "sections": [
            ("Ce qui fixe le prix", "La maison, les acres, les bâtiments, le zonage, l'eau et la fosse. Une « fermette de rêve » sans comparables d'acres se paie trop cher. On sépare la valeur résidentielle de la valeur agricole ou loisir."),
            ("Zonage et CPTAQ", "Une terre agricole n'autorise pas tous les projets (cheval, location, subdivision). Vérifiez avant l'offre. Un courtier local pose la question ; un notaire la confirme."),
            ("Inspection rurale", "Grange, atelier, drainage, puits, fosse dimensionnée. Ce n'est pas la même checklist qu'un bungalow. Budgetz le bon inspecteur."),
            ("Mise en marché", "Photos de saison, acreage exact, bâtiments sans enjoliver. Acheteurs locaux et parfois hors région. L'équipe a déjà inscrit ce type de bien dans le Haut-Saint-François."),
        ],
        "faqs": [
            ("Fermette ou ferme ?", "Une fermette est souvent une résidence avec terre et bâtiments, sans exploitation commerciale pleine. Une ferme se juge aussi aux revenus et au quota. Les comparables ne se mélangent pas."),
            ("Peut-on financer une fermette comme une maison ?", "Parfois, selon le prêteur, le zonage et la part résidentielle. Une préautorisation rurale n'est pas une préautorisation urbaine. Parlez-en avant d'offrir."),
            ("Où voyez-vous le plus de fermettes ?", "Haut-Saint-François : Coaticook, Compton, Clifton, Cookshire-Eaton. Ailleurs en Estrie aussi, au cas par cas."),
            ("Par où commencer ?", "Critères (acres, bâtiments, budget), puis comparables. Contactez l'équipe ou voyez les inscriptions actives."),
        ],
        "links": [("Documents terrain", "article-documents-vente-terrain.html"), ("Documents maison", "article-documents-vente-maison.html"), ("Saint-Isidore-de-Clifton", "regions/saint-isidore-de-clifton.html"), ("Coaticook", "regions/coaticook.html"), ("Terrains", "article-terrain-estrie.html")],
    },
    {
        "file": "chalet-estrie.html",
        "title": "Acheter ou vendre un chalet en Estrie | CDF",
        "desc": "Chalets à Magog, Orford, lacs Estrie : quatre-saisons, fosses, accès. Courtiers Chiasson de Francesco à Sherbrooke.",
        "h1": "Acheter ou vendre un chalet en Estrie",
        "lead": "L'équipe Chiasson de Francesco accompagne chalets et résidences de villégiature en Estrie : Magog, Orford, Eastman, lacs Memphrémagog, Massawippi et Aylmer : en distinguant le trois-saisons du quatre-saisons.",
        "sections": [
            ("Trois lacs, une montagne, des règles", "Memphrémagog n'est pas Massawippi, Aylmer n'est pas Orford ski. Vue, accès à l'eau, quai et bande riveraine changent le prix. Voir notre guide bord de lac."),
            ("Saisonnier vs principal", "Isolation, chauffage, accès hivernal, assurance. Un chalet vendu « habitable à l'année » se vérifie à l'inspection, pas dans le titre de l'annonce."),
            ("Fosses et environnement", "Hors égouts, la fosse et parfois le règlement riverain tuent un projet de rénovation. Budgetz la mise aux normes avant d'offrir le « prix chalet »."),
            ("Vendre un chalet", "Photos d'eau et de saison, honnêteté sur le poêle et le chemin. Le printemps aide souvent. Un prix Magog lac sur un rang Orford se brade ensuite."),
        ],
        "faqs": [
            ("Peut-on louer à court terme ?", "Selon la municipalité et, le cas échéant, la copropriété. Magog, Orford et les villages n'ont pas les mêmes règles. Vérifiez avant d'acheter pour un revenu Airbnb."),
            ("Chalet ou condo de montagne ?", "Deux produits. Le condo a des charges et un syndicat. Le chalet a la fosse et l'entretien. Sutton/Bromont/Orford : voyez aussi les pages région."),
            ("Financement plus difficile ?", "Souvent, surtout saisonnier ou hors normes. Une préautorisation claire évite une offre qui tombe."),
            ("Vous vendez des chalets ?", "Oui, lorsque nous avons le mandat, surtout Magog, Orford et les lacs."),
        ],
        "links": [("Bord de lac", "article-bord-de-lac-estrie.html"), ("Orford", "regions/orford.html"), ("Magog", "regions/magog.html")],
    },
    {
        "file": "plex-sherbrooke.html",
        "title": "Acheter ou vendre un plex à Sherbrooke | CDF",
        "desc": "Duplex, triplex et multiplex à Sherbrooke : loyers, rénos, quartiers. Équipe Chiasson de Francesco, RE/MAX.",
        "h1": "Acheter ou vendre un plex à Sherbrooke",
        "lead": "L'équipe Chiasson de Francesco accompagne plex et multiplex à Sherbrooke : Les Nations, Lennoxville, Fleurimont : un investissement qui se juge aux loyers réels et à l'état, pas à un rendement théorique.",
        "sections": [
            ("Le rendement n'est pas l'annonce", "Loyers au bail, vacance, taxes, assurances, travaux. Un plex « 6 % » dans une pub Facebook ignore souvent le toit. Notre article investir à Sherbrooke complète cette page."),
            ("Quartiers", "Lennoxville : parfois étudiant. Nations : plus urbain. Fleurimont/Mont-Bellevue : plus familial, loyers différents. Un plex Windsor n'est pas un plex King."),
            ("Due diligence", "Baux, déclaration du vendeur, inspection (toiture, fondations, logements occupés), règlements municipaux. Une visite d'un seul logement ne suffit pas."),
            ("Vendre un plex", "Dossier locatif propre, photos des logements, prix collé aux ventes de plex du même secteur : pas à une unifamiliale voisine."),
        ],
        "faqs": [
            ("Premier plex : par où commencer ?", "Préautorisation investisseur, secteur, nombre d'unités, et une lecture des baux avant l'émotion. Jade, Pierre-Olivier et Marco accompagnent aussi ce premier pas."),
            ("Occupation d'un logement par l'acheteur ?", "Possible selon les baux et la loi. Ce n'est pas automatique. On le cadre dans l'offre."),
            ("Plex ou condo locatif ?", "Le plex, vous gérez l'immeuble. Le condo, vous payez des charges et un syndicat. Deux risques, deux rendements."),
            ("Vous inscrivez des plex ?", "Oui, selon les mandats. Voyez aussi vendremonplex.com dans le réseau de l'équipe."),
        ],
        "links": [("Documents pour vendre un plex", "article-documents-vente-plex.html"), ("Vendre un plex", "article-vendre-plex-sherbrooke.html"), ("Investir à Sherbrooke", "article-investir-sherbrooke.html"), ("Les Nations", "regions/les-nations.html"), ("Lennoxville", "regions/lennoxville.html")],
    },
    {
        "file": "courtier-acheteur-estrie.html",
        "title": "Courtier acheteur en Estrie | Sherbrooke | CDF",
        "desc": "Être représenté à l'achat à Sherbrooke et en Estrie : recherche, inspection, offre. Équipe Chiasson de Francesco.",
        "h1": "Courtier acheteur à Sherbrooke et en Estrie",
        "lead": "L'équipe Chiasson de Francesco représente les acheteurs en Estrie : filtres Centris, lecture des comparables par quartier, visites et négociation des conditions : pas seulement un rabais sur le prix demandé.",
        "sections": [
            ("Pourquoi un courtier côté acheteur", "Le vendeur a souvent déjà le sien. Le vôtre lit la déclaration, le zonage, et ce que la rue a vraiment vendu. À Lennoxville ce n'est pas Fleurimont ; à Magog lac ce n'est pas Orford ski."),
            ("Rémunération", "Au Québec, c'est prévu aux contrats. Souvent une part de la commission de listage rémunère le courtier collaborateur. On l'explique avant de visiter sérieusement : pas après l'offre."),
            ("Offre et inspection", "Prix, délais, inclusions, tests (fosse, granulats selon le cas). Voir nos articles offre d'achat et inspection. Une offre trop émotive se paie chez le notaire."),
            ("Premier achat et hors région", "Préautorisation, SCHL si moins de 20 %, calendrier. Acheteurs hors Estrie : Marco travaille aussi à distance et en anglais."),
        ],
        "faqs": [
            ("Est-ce vraiment gratuit pour l'acheteur ?", "Ce n'est pas « gratuit » : c'est contractuel. Dans beaucoup de transactions résidentielles, la collab est prévue au listage. Chaque dossier se confirme par écrit."),
            ("Puis-je visiter des portes ouvertes seul ?", "Oui. Un courtier structure ensuite l'offre et les conditions. C'est là que l'erreur coûte."),
            ("Vous représentez aussi le vendeur ?", "Selon le mandat. Les règles d'agence (dont la double représentation) s'expliquent clairement. Pas de zone grise."),
            ("Par où commencer ?", "Préautorisation, trois critères (secteur, type, budget), puis recherche. Page acheter ou contact."),
        ],
        "links": [("Acheter", "acheter.html"), ("Offre d'achat", "article-offre-achat-quebec.html"), ("Inspection", "article-inspection-maison-estrie.html")],
    },
]

ARTICLES = [
    {
        "file": "article-vendre-hiver-estrie.html",
        "title": "Vendre sa maison l'hiver en Estrie | CDF",
        "headline": "Vendre l'hiver en Estrie : moins de visites, parfois de meilleurs acheteurs",
        "desc": "Neige, photos et prix : ce qui change vraiment quand on affiche une maison à Sherbrooke entre novembre et mars.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Vendre",
        "author": "Jade Sirois",
        "author_page": "jade.html",
        "kicker": "L'hiver estrien n'arrête pas les ventes. Il change le trafic, les photos et le type d'acheteur : surtout hors villégiature.",
        "sections": [
            ("Moins de curieux, plus de motivés", "À Sherbrooke, un bungalow juste en janvier se vend. Un chalet Orford trop cher attend le dégel. Le calendrier dépend du produit, pas d'une règle « on n'affiche jamais l'hiver »."),
            ("Photos et entrée", "Neige propre, entrée dégagée, lumière. Une allée glacée et une pièce sombre tuent la visite. Le home staging d'hiver, c'est surtout ça."),
            ("Le prix reste le prix", "Moins d'inscriptions n'autorise pas une surcote. Les acheteurs sérieux comparent les ventes d'automne. Un bien 10 % trop haut attend avril : et signale un problème."),
            ("Quand attendre quand même", "Si vous vendez un bord de lac « pour la photo d'été » et que le bâtiment n'est pas prêt, le questionnaire de timing aide. L'équipe ne pousse pas un affichage pour remplir Centris."),
        ],
    },
    {
        "file": "article-notaire-immobilier-quebec.html",
        "title": "Notaire immobilier au Québec | rôle et délais | CDF",
        "headline": "Le notaire dans une transaction immobilière au Québec",
        "desc": "Titres, ajustements, acte : ce que le notaire fait (et ne fait pas) quand vous achetez ou vendez à Sherbrooke.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Acheter",
        "author": "Pierre-Olivier Chiasson",
        "author_page": "pierre-olivier.html",
        "kicker": "Au Québec, on passe chez le notaire, pas chez l'avocat de closing américain. Mal cadrer les délais de l'acte, c'est faire tomber une offre pourtant acceptée.",
        "sections": [
            ("Ce qu'il vérifie", "Titres, servitudes, hypothèques à radier, ajustements de taxes et de loyers. Sur un lac ou une fermette, les droits d'eau et le zonage remontent souvent ici : trop tard si l'offre était déjà ferme."),
            ("Ce qu'il ne remplace pas", "L'inspection, l'évaluation municipale, le courtier. Un notaire ne vous dit pas si le prix est le marché de Fleurimont. Il dit si vous pouvez publier l'acte."),
            ("Délais", "L'offre prévoit une date d'acte. Trop serrée après l'inspection, et tout le monde court. Trop lointaine, et le vendeur s'impatiente. Un courtier calibre ça avec votre notaire."),
            ("Choisir", "Vous pouvez proposer votre notaire. En Estrie, un notaire qui connaît les fosses et les lacs évite des allers-retours. L'équipe travaille avec plusieurs études de Sherbrooke."),
        ],
    },
    {
        "file": "article-droits-mutation-sherbrooke.html",
        "title": "Droits de mutation à Sherbrooke | taxe de bienvenue | CDF",
        "headline": "Droits de mutation (taxe de bienvenue) à Sherbrooke et en Estrie",
        "desc": "La taxe de bienvenue n'est pas un détail : comment la prévoir à Sherbrooke, Magog ou ailleurs en Estrie, sans inventer les taux.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Acheter",
        "author": "Jade Sirois",
        "author_page": "jade.html",
        "kicker": "Les droits de mutation se calculent sur le plus élevé du prix ou de la valeur marchande retenue, selon les tranches de la municipalité. Sherbrooke n'a pas le même règlement qu'une petite ville.",
        "sections": [
            ("Ce que c'est", "Un impôt municipal à l'achat, souvent appelé taxe de bienvenue. Il s'ajoute au notaire, à l'inspection et aux ajustements. Notre guide des frais cachés le place dans le budget total."),
            ("Sherbrooke vs ailleurs", "Chaque ville fixe ses tranches. Magog, Bromont, Coaticook : vérifiez le site de la municipalité ou demandez une estimation à votre notaire. Une page web d'équipe ne remplace pas le calcul officiel."),
            ("Exemptions", "Certains transferts (succession, parfois entre conjoints selon les règles) peuvent être traités autrement. Ce n'est pas automatique. Le notaire tranche, pas l'annonce Centris."),
            ("Dans l'offre", "Prévoir le cash le jour de l'acte. Un premier acheteur qui a mis toute sa mise de fonds dans le prix découvre la taxe trop tard."),
        ],
    },
    {
        "file": "article-contre-offre-quebec.html",
        "title": "Contre-offre immobilière au Québec | CDF",
        "headline": "Contre-offre au Québec : prix, délais et ce qu'il ne faut pas lâcher",
        "desc": "Comment répondre à une offre à Sherbrooke : prix, inspection, inclusions. Conseils de l'équipe Chiasson de Francesco.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Vendre",
        "author": "Marco De Francesco",
        "author_page": "marco.html",
        "kicker": "Une contre-offre n'est pas un « non » poli. C'est un nouveau document. Mal rédigée, elle fait fuir le seul acheteur sérieux de la semaine.",
        "sections": [
            ("Prix vs conditions", "Reprendre 10 000 $ et tuer l'inspection, c'est souvent perdre. En Estrie, hors enchères rares, les conditions tiennent plus longtemps qu'à Montréal 2021. Un courtier sépare l'ego du dossier."),
            ("Délais de réponse", "Trop longs, l'acheteur passe à l'autre maison. Trop courts, vous signez la panique. On calibre selon le trafic réel des visites, pas selon l'espoir."),
            ("Inclusions", "Lave-vaisselle, stores, cabanon, quai : écrivez-les. « On s'entendra » se discute mal chez le notaire."),
            ("Plusieurs offres", "Rare mais possible sur un bien juste. Règles d'équité, copies, délais. L'équipe gère ça sans théâtre : et sans inventer une guerre d'enchères qui n'existe pas."),
        ],
    },
    {
        "file": "article-declaration-vendeur.html",
        "title": "Déclaration du vendeur au Québec | CDF",
        "headline": "La déclaration du vendeur : ce qui doit être dit, et ce qui se paie plus tard",
        "desc": "Fuites, fosses, sinistres : pourquoi une déclaration incomplète coûte plus cher qu'une réparation avouée à Sherbrooke.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Vendre",
        "author": "Pierre-Olivier Chiasson",
        "author_page": "pierre-olivier.html",
        "kicker": "Cacher une infiltration « parce que ça n'a pas coulé cet hiver » n'est pas une stratégie. Au Québec, la déclaration du vendeur suit le dossier jusqu'après l'acte.",
        "sections": [
            ("À quoi elle sert", "Elle informe l'acheteur de ce que vous savez : toiture, fondations, fosses, sinistres, zonage connu. Un courtier vous aide à la remplir sans jargon, pas à la vider."),
            ("Ce que l'inspection trouve quand même", "L'inspecteur n'efface pas une déclaration fausse. Il ajoute une couche. Les deux se lisent ensemble dans l'offre."),
            ("Vendeur héritier ou absent", "« Je ne vis pas là, je ne sais pas » a des limites. On documente l'ignorance de bonne foi ; on n'invente pas un bâtiment parfait."),
            ("Côté acheteur", "Lisez-la avant d'offrir, pas dans le stationnement du notaire. Un courtier acheteur la relie aux visites et aux questions d'inspection."),
        ],
        "extra_links": [("Documents pour vendre une maison", "article-documents-vente-maison.html")],
    },
    {
        "file": "article-pyrrhotite-estrie.html",
        "title": "Pyrrhotite et fondations en Estrie | CDF",
        "headline": "Pyrrhotite, pyrite, granulats : quoi vérifier en Estrie avant d'acheter",
        "desc": "Certaines fondations au Québec ont des problèmes de granulats. En Estrie, on ne diagnostique pas sur une page web : on oriente vers l'inspection et l'expert.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Acheter",
        "author": "Marco De Francesco",
        "author_page": "marco.html",
        "kicker": "La pyrrhotite a surtout marqué d'autres régions du Québec ; la pyrite aussi. En Estrie, le bon réflexe n'est pas la panique ni le déni : c'est l'année de construction, l'inspecteur, et un expert si le rapport le dit.",
        "sections": [
            ("Ce qu'on ne fera pas ici", "Pas de carte magique « zones sûres ». Pas de statistique inventée. Les programmes et les recours évoluent ; un courtier n'est pas un ingénieure en matériaux."),
            ("Le bon ordre", "Offre avec condition d'inspection. Si l'inspecteur voit des signes (fissures, écaillage atypique), on arrête et on réfère. Un test de granulat se décide alors, pas sur un groupe Facebook."),
            ("Déclaration et documents", "Factures de fondation, année, sinistres. Une maison des années 1990-2010 dans certaines régions du Québec justifie plus de questions. Sherbrooke n'est pas Trois-Rivières ; chaque immeuble est un cas."),
            ("Rôle du courtier", "Poser les questions, ménager le délai d'inspection, ne pas presser une levée de conditions. L'équipe Chiasson de Francesco préfère perdre une transaction qu'enfermer un acheteur dans un dossier technique mal lu."),
        ],
    },
    {
        "file": "article-schl-premier-acheteur.html",
        "title": "SCHL et mise de fonds au Québec | premier acheteur | CDF",
        "headline": "Mise de fonds et assurance SCHL : ce qu'un premier acheteur en Estrie doit savoir",
        "desc": "Moins de 20 % de mise de fonds : l'assurance prêt existe. On explique le principe, pas vos primes : ça, c'est le prêteur.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Acheter",
        "author": "Jade Sirois",
        "author_page": "jade.html",
        "kicker": "À Sherbrooke, beaucoup de premiers achats se font avec moins de 20 % de mise de fonds. L'assurance prêt (SCHL ou équivalent) n'est pas un détail : elle change le paiement, pas seulement « le droit d'acheter ».",
        "sections": [
            ("Le principe", "Sous 20 %, le prêteur exige généralement une assurance prêt hypothécaire. La prime se capitalise souvent dans le prêt. Les règles et les taux changent : votre courtier hypothécaire donne le chiffre du jour, pas cette page."),
            ("Ce que ça change dans l'offre", "La préautorisation doit coller au type de bien (unifamiliale, plex, chalet). Un chalet saisonnier ou un plex de 5 logements n'entre pas dans la même case qu'un bungalow Fleurimont."),
            ("Frais autour", "Droits de mutation, notaire, inspection. Une mise de fonds « au maximum du prix » sans réserve pour la taxe de bienvenue casse le closing. Voir frais cachés."),
            ("Rôle du courtier immobilier", "On aligne le bien sur ce que le prêteur finance. On ne promet pas une prime. Pierre-Olivier, Marco et Jade travaillent avec votre dossier hypothécaire, pas à sa place."),
        ],
    },
    {
        "file": "article-magog-ou-sherbrooke.html",
        "title": "Magog ou Sherbrooke : où acheter ? | CDF",
        "headline": "Magog ou Sherbrooke : comment choisir (sans slogan villégiature)",
        "desc": "Services, lac, budget, trajet : les vrais écarts entre acheter à Magog et à Sherbrooke, par des courtiers qui font les deux.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Acheter",
        "author": "Marco De Francesco",
        "author_page": "marco.html",
        "kicker": "Magog n'est pas « Sherbrooke avec un lac ». Sherbrooke n'est pas « Magog sans charme ». Le bon choix dépend du quotidien de janvier, du budget, et du type de bien.",
        "sections": [
            ("Sherbrooke", "Pôle d'emplois, universités, hôpitaux, plus de volume d'unifamiliales et de plex. Quartiers très différents (Lennoxville vs Fleurimont vs Nations). Voir les pages quartier."),
            ("Magog", "Centre-ville, Memphrémagog, villégiature, parfois plus cher pour l'équivalent bâti. Un condo en ville n'est pas un bord de lac. Orford est à côté, ce n'est pas Magog."),
            ("Le trajet", "Beaucoup navettent. Mesurez l'heure de pointe, pas Instagram. Rock Forest est souvent le compromis géographique : avec son propre marché."),
            ("Comment on aide", "On ne « vend » pas une ville. On aligne budget, type de bien et usage. L'équipe Chiasson de Francesco travaille les deux tous les jours."),
        ],
    },
    {
        "file": "article-bromont-ou-sutton.html",
        "title": "Bromont ou Sutton : où acheter ? | CDF",
        "headline": "Bromont ou Sutton : deux montagnes, deux villages, deux marchés",
        "desc": "Ski, village, condos et maisons : comment départager Bromont et Sutton sans copier un prix de station.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Acheter",
        "author": "Pierre-Olivier Chiasson",
        "author_page": "pierre-olivier.html",
        "kicker": "Choisir entre Bromont et Sutton sur le nom de la montagne, c'est comme choisir Sherbrooke ou Magog sur le nom de la rivière. Le produit (condo ski vs maison de village) décide.",
        "sections": [
            ("Bromont", "Plus d'infrastructures sportives, plus de volume, navetteurs Rive-Sud fréquents. Condos de pente et lotissements ne se comparent pas. Voir la page Bromont."),
            ("Sutton", "Village plus « Cantons », arts, ski, marché souvent plus artisanal. Copropriétés de montagne avec règles de location à lire. Voir la page Sutton."),
            ("Lac-Brome au milieu", "Knowlton n'est ni ski ni Bromont station. Si vous voulez le village lacustre, c'est un troisième marché. Voir Lac-Brome."),
            ("Location courte durée", "Syndicat + municipalité. Plusieurs immeubles l'encadrent ou l'interdisent. Acheter « pour Airbnb » sans lire le règlement n'est pas un plan."),
        ],
    },
    {
        "file": "article-vendre-plex-sherbrooke.html",
        "title": "Vendre un plex à Sherbrooke | dossier locatif | CDF",
        "headline": "Vendre un plex à Sherbrooke : loyers, travaux et prix d'investisseur",
        "desc": "Un plex ne se vend pas comme une unifamiliale. Dossier locatif, photos des logements, comparables. Équipe Chiasson de Francesco.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Vendre",
        "author": "Pierre-Olivier Chiasson",
        "author_page": "pierre-olivier.html",
        "kicker": "L'acheteur d'un plex lit les baux avant la cuisine du 2e. Un dossier locatif flou à Sherbrooke, c'est des conditions qui s'allongent : ou une offre qui ne vient pas.",
        "sections": [
            ("Le dossier", "Baux, loyers, dépôts, travaux faits et à faire, taxes. Un toit à 15 ans se dit. Un « on verra » se négocie contre le prix."),
            ("Photos", "Tous les logements, parties communes, compteurs. Un plex montré comme une maison unifamiliale attire le mauvais acheteur."),
            ("Prix", "Ventes de plex du même secteur et du même nombre d'unités. Lennoxville n'est pas Fleurimont. Un multiple magique « × loyers » sans état du bâtiment ment."),
            ("Occupation vendeur", "Si vous occupez un logement, dites-le. L'offre devra le traiter. L'équipe prépare ça avant l'affiche."),
        ],
        "extra_links": [("Documents pour vendre un plex", "article-documents-vente-plex.html")],
    },
    {
        "file": "article-prix-affiche-vs-vente.html",
        "title": "Prix demandé vs prix de vente en Estrie | CDF",
        "headline": "Prix affiché et prix de vente : l'écart qui coûte des semaines en Estrie",
        "desc": "À Sherbrooke, un écart trop grand entre l'affiche et les ventes closes brûle un bien. Comment l'équipe ancre le premier prix.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Vendre",
        "author": "Marco De Francesco",
        "author_page": "marco.html",
        "kicker": "Les acheteurs ne paient pas le prix demandé. Ils paient ce que les comparables ont clos. Un affichage 12 % au-dessus, c'est souvent trois baisses publiques et un signal de détresse.",
        "sections": [
            ("Pourquoi on survend l'affiche", "Évaluation municipale, voisin qui « a demandé plus », rénos dont vous vous souvenez au dollar. Rien de tout ça n'est une vente close."),
            ("Ce que le marché lit", "Jours sur Centris, historique de baisses, photos. En Estrie, hors micro-enchères, le premier prix est le levier. Voir délai de vente et évaluation marchande."),
            ("Stratégie honnête", "Ancrer sur 3 à 5 ventes du même type dans le même secteur. Ajuster état et terrain. Si le propriétaire refuse, on le dit : on n'invente pas une file d'acheteurs."),
            ("Après deux semaines", "Pas de trafic qualifié = on révise. On n'attend pas la saison suivante par orgueil."),
        ],
    },
    {
        "file": "article-copropriete-documents-quebec.html",
        "title": "Documents de copropriété au Québec | quoi demander | CDF",
        "headline": "Documents de copropriété : la liste avant d'offrir à Sherbrooke",
        "desc": "Déclaration, PV, fonds, règlements : ce qu'un acheteur de condo à Sherbrooke doit obtenir, et ce qu'un vendeur doit préparer.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Acheter",
        "author": "Jade Sirois",
        "author_page": "jade.html",
        "kicker": "Le plus bel appartement des Nations ne vaut rien si le fonds de prévoyance est vide et qu'une toiture s'en vient. Les documents, pas la visite Instagram, tranchent.",
        "sections": [
            ("La liste minimale", "Déclaration de copropriété, règlement, états financiers, PV d'assemblées, étude du fonds si elle existe, état des charges, litiges connus. Un vendeur organisé vend plus vite."),
            ("Quoi y lire", "Hausses de charges, cotisations spéciales, interdiction de location courte, animaux, rénos. Voir aussi nos articles condo achat et vente."),
            ("Délais dans l'offre", "Prévoir le temps d'obtenir et de lire. Une condition « documents » trop courte force des levées à l'aveugle."),
            ("Petit immeuble vs tour", "Une copropriété de 6 unités n'a pas la même gouvernance qu'une tour. Les deux peuvent être saines ou non. On ne généralise pas sur le nombre d'étages."),
        ],
    },
    {
        "file": "article-location-courte-duree-estrie.html",
        "title": "Location courte durée Magog, Orford, Sutton | CDF",
        "headline": "Airbnb et location courte durée en Estrie : vérifiez avant d'acheter",
        "desc": "Magog, Orford, Sutton, Sherbrooke : la location courte durée dépend du règlement municipal et de la copropriété. Pas d'un espoir de rendement.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Investissement",
        "author": "Marco De Francesco",
        "author_page": "marco.html",
        "kicker": "Acheter un chalet « pour le louer sur les plateformes » sans lire le règlement, c'est acheter un conflit. En Estrie, les règles changent d'une municipalité à l'autre : et d'un syndicat à l'autre.",
        "sections": [
            ("Deux verrous", "La ville (ou la MRC) et, si copropriété, la déclaration. L'un des deux suffit à interdire. CITQ et assurances s'ajoutent ensuite. Cette page ne remplace pas le greffe municipal."),
            ("Magog, Orford, lacs", "Villégiature ≠ droit de louer trois jours. Bandes riveraines et voisinage pèsent. Demandez le règlement en vigueur, pas un souvenir de 2019."),
            ("Sutton, Bromont", "Condos de montagne : souvent les règles les plus strictes. Lisez avant l'offre, pas après la première réservation refusée."),
            ("Sherbrooke", "Plus urbain, pas forcément plus permissif. Quartier par quartier. Un plex « Airbnb » illégal n'est pas un business plan."),
        ],
    },
    {
        "file": "article-photos-mise-en-marche.html",
        "title": "Photos immobilières en Estrie | mise en marché | CDF",
        "headline": "Photos d'annonce : ce qui fait visiter (et ce qui fait passer) en Estrie",
        "desc": "Lumière, neige, lac, pièces vides : comment l'équipe Chiasson de Francesco prépare les photos avant Centris.",
        "date": "18 août 2026",
        "published": "2026-08-18",
        "tag": "Vendre",
        "author": "Jade Sirois",
        "author_page": "jade.html",
        "kicker": "En Estrie, une photo de lac trop sombre ou une cuisine encombrée filtre les acheteurs avant la première visite. Le home staging commence souvent par le déclencheur, pas par un sofa neuf.",
        "sections": [
            ("Ce qui se voit tout de suite", "Lumière naturelle, verticales droites, frigo sans aimants, lits faits. Un grand angle qui déforme une pièce de 9 pieds n'aide personne."),
            ("Saison", "Bord de lac et montagne : la saison de la photo doit coller au produit. Un chalet photographié sous la pluie en novembre se vend plus mal qu'un bungalow Fleurimont bien éclairé le même jour."),
            ("Ce qu'on ne truque pas", "Pas de ciel inventé qui promet un quai inexistant. L'acheteur visiteur punit le décalage. L'équipe préfère une photo honnête et un prix juste."),
            ("Après les photos", "Description, ordre des clichés, plan si utile. Voir home staging. Un courtier qui « prend trois photos au cellulaire » n'a pas fini le travail de mise en marché."),
        ],
    },
]


def main() -> None:
    extras = [
        ("Vendre une propriété", "../vendre.html"),
        ("Acheter en Estrie", "../acheter.html"),
    ]
    skip = {h for _, h in extras}
    for page in REGIONS:
        page["related"] = extras + [(t, h) for t, h in page["related"] if h not in skip]
        path = ROOT / "regions" / f"{page['slug']}.html"
        path.write_text(render_region(page), encoding="utf-8")
        print("wrote", path.relative_to(ROOT))
    for s in SERVICES:
        write_service(s)
    for a in ARTICLES:
        write_article(a)


if __name__ == "__main__":
    main()
